### ISSUE TITLE
Question: Does this support mounting public s3 buckets

### ISSUE THREAD

**Issue by scottcain** [cblomart/s3vol#1]
Before I head down the path of using what looks like a very useful tool, I have a question: can I use this plugin to mount a public S3 bucket, so that I don't need to provide the access and secret keys?  Thanks!

**Comment by cblomart** [comment]
It's an old one but i would highly advise not to use public S3 buckets!

**Comment by scottcain** [comment]
I have absolutely no memory of why I wanted to do this, but I didn't use a public s3 bucket for it. Thanks.
